### ISSUE TITLE
make bower optional

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-try#101]
We don't want to download bower unless the host application actually needs it.

Now that: https://github.com/emberjs/ember.js/pull/13022 has landed, we need to get the ball rolling on dropping bower from our default installations.

RFC tracking issue: https://github.com/ember-cli/rfcs/issues/41

**Comment by kategengler** [comment]
@stefanpenner Do you have any more details on what is required here?

I believe bower isn't a requirement of ember-try unless the `bower` key is used in the config. It is currently used in the default config, so it is required by anybody not overriding the config, but I believe it has to stay that way until the default scenarios are all available via npm (release, beta and canary).

**Comment by stefanpenner** [comment]
my thoughts where to identify what required it, and then optionally download it if the users truly need it. Rather then forcing all ember-cli installs to download it.

Although we don't quite have all versions of ember on npm, hopefully we will soon. And if we can make ember try lazily depend on bower (by downloading it on-demand) we are on the path to reducing ember-cli's download size dramatically.

**Comment by kategengler** [comment]
@stefanpenner I understand the motivations. What I'm saying is that that I _think_ it's already optional from the perspective of ember-try. It doesn't use bower programmatically and will only try to read bower.json or use `bower` through `spawn` if there is a `bower` key in the config. 

The default config (and the one generated by ember-cli) both currently have a `bower` key, but once that is removed, it won't try to use bower (and wouldn't have downloaded it either way -- just failed hard because of the absence).

**Comment by stefanpenner** [comment]
@kategengler you are correct!
