### ISSUE TITLE
npm 4 strangeness

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-try#140]
npm 4 + a scenario involving bower is giving strange errors.

https://github.com/ember-vr/ember-aframe-shim/pull/26
https://travis-ci.org/ember-vr/ember-aframe-shim/jobs/261179127#L9266-L9296

**Comment by kategengler** [comment]
@kellyselden replicated locally. I also asked him to try manually editing package.json and running `npm install`, but there was no error in that case.

**Comment by kategengler** [comment]
@kellyselden Can you see if this still happens in v0.2.19?

**Comment by kellyselden** [comment]
It got better. Now it's only failing "ember-default" (v0.2.20)

**Comment by jacobq** [comment]
I'm not sure if this is related, but I think it definitely qualifies as "npm 4 strangeness":
I am [getting](https://travis-ci.org/locks/ember-localstorage-adapter/jobs/341573811#L2555) the error shown below during the `ember-beta` scenario (others seem OK), but it goes away if I bump npm to v5.x. Also, when I run locally, [I get](https://github.com/locks/ember-localstorage-adapter/pull/223#issuecomment-365665985) `Error: Cannot find module 'bower'` *unless I pass `--skip-cleanup`*.

```
=== Scenario: ember-beta =======================================================
Missing npm packages: 
Package: ember-source
  * Specified: https://s3.amazonaws.com/builds.emberjs.com/beta/shas/84c8ecac85175571047690540f1dea7e62115c64.tgz
  * Installed: (not installed)
Run `npm install` to install missing dependencies.
Stack Trace and Error Report: /tmp/error.dump.f4b47819dc2c4c48c99b2e1c479fd993.log
An error occurred in the constructor for ember-cli-dependency-checker at /home/travis/build/locks/ember-localstorage-adapter/node_modules/ember-cli-dependency-checker
```

**Comment by kategengler** [comment]
@jacobq I don't believe this is the same issue. I'm not 100% sure, but I think your issue may be resolved by removing your mostly empty `bower.json`

**Comment by jacobq** [comment]
@kategengler Thanks for the tip. Indeed, the bower error disappears when I remove `bower.json`. However, isn't that a bug then? I didn't think there was anything wrong with having an empty `bower.json`. Although I'm not using bower to load this package, it does appear to be published on bower, [which is why I didn't think I should delete that file](https://bower.io/docs/creating-packages/#register).

I guess bower users (if there are any) can just keep using the old version, and aside from curiosity I don't really care about npm@4 since it sounds like it's been [dropped in Ember v3.x](https://github.com/ember-cli/ember-cli/pull/7482) anyway.
 
![bower](https://user-images.githubusercontent.com/1633459/36258772-8fde68e8-1221-11e8-954e-da749af56596.png)

**Comment by kategengler** [comment]
@jacobq `npm@4` is not dropped in `ember-cli`. The issue you linked to is open and argues in favor of dropping it because of a PR that was later closed but not merged. 

ember addons aren't consumable via `bower`, without either specific work to provide built files, or a lot of work on the consuming side. I don't see that sort of setup in `ember-localstorage-adapter`. With 3.0, `ember` itself has stopped publishing to `bower`. 

If you add back `bower` as a dependency in package.json, I believe the empty `bower` file won't cause an error. I'm not sure I'd consider the error a bug, because if you want to have a bower.json, you need to have it as a dep.

**Comment by jacobq** [comment]
@kategengler Ah, OK, thank you for explaining that. I must have missed that in the upgrade process (last version of this addon was old enough (using ember-cli 2.7) that I think bower was automatically brought in then so it was never added to the `devDependencies` list).

**Comment by rwjblue** [comment]
Bower support has been removed, closing...
