### ISSUE TITLE
npm 5 & 6 failing to switch npm deps

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-try#167]
As seen [here](https://github.com/kellyselden/ember-data-fetch-support/pull/107), switching to npm 5 causes the ember-data overrides to not work. The dependency checker fails saying ember-data is not installed (only for certain scenarios).

https://travis-ci.org/kellyselden/ember-data-fetch-support/jobs/319855014#L1080

**Comment by kategengler** [comment]
@kellyselden Do you know if this is still a problem with 1.0?

**Comment by kellyselden** [comment]
unfortunately yes https://travis-ci.org/kellyselden/ember-data-application-adapter-service/jobs/425212553

**Comment by kategengler** [comment]
Thanks for trying it again! To separate the issue of npm5 from the issues in #201, could you try it with an ember-try config with just the specific version scenarios (remove release/beta scenarios)?

**Comment by kellyselden** [comment]
Does this work? https://travis-ci.org/kellyselden/ember-data-application-adapter-service/builds/425212549 you can see the 2.16 scenario fails too.

**Comment by kategengler** [comment]
Perfect, thanks!

**Comment by kellyselden** [comment]
Appears to be happening with npm 6 too.

**Comment by kellyselden** [comment]
Hopefully this helps, it has the travis-ci history of before and after the ember-try downgrade. https://github.com/ember-vr/ember-aframe/pull/119

**Comment by kellyselden** [comment]
Here's another example with a lockfile https://github.com/kellyselden/ember-test-setup/pull/20.

**Comment by kategengler** [comment]
Narrowing the problem down, it seems like it is older node + newer npm, when there is a lockfile before `ember-try` runs

**Comment by mansona** [comment]
@kategengler what do you mean by "older node + newer npm"? The reason why I ask is because I'm on newest node and npm and it fails for me (I'm running locally).

Interestingly as soon as I delete the package-lock.json it starts working again 🤔 and it doesn't seem like there is a package-lock.json generated between try scenarios

**Comment by mansona** [comment]
Howdy folks 👋 it's me again 😂 

I've come across this issue again with something that is relatively new so it has always had ember-try 1.0 and I am motivated to help try and fix this because it feels silly downgrading in this case 😄 

@kategengler on the idea of "older node + newer npm" I would love to know more about your thoughts. I am working on https://github.com/empress/guidemaker/pull/9 and ran a little experiment trying the ember-try scenarios with multiple node versions and it didn't seem to help the situation 🤔 

I would love to contribute and help fix this if you had any guidance for where I should start looking 👍

**Comment by kategengler** [comment]
Hi @mansona! Unfortunately, I don't really have any guidance -- this issue has been very hard to nail down.  

I recently recreated it reliably with this repo, at least on my machine. Can you confirm it happens consistently on your machine with this repo/branch too? 

https://github.com/kategengler/torii-test/tree/ember-try-boom

**Comment by mansona** [comment]
@kategengler thanks! sometimes knowing that you have to start from the beginning is enough to start with 😂 

So I ended up doing a `git bisect` on this and found out that the bad commit was https://github.com/ember-cli/ember-try/commit/d84fc75700e8fd0d94e02b20dd2647c44f8b6a9f which was merged in #171 

Doing some local tests and some research into the npm docs it seems like the best way forward is to completely remove the `npm prune` command 🤔 I have done that in #280 and it seems to be working perfectly for my original PR on Guidemaker: https://travis-ci.com/empress/guidemaker/builds/100624665

I also did a test locally to verify that ember-try was indeed updating the Ember version that was being used in a test 👍

**Comment by kellyselden** [comment]
That's great work @mansona!

**Comment by kategengler** [comment]
@mansona Thanks for this work!

The `npm prune` was added to remove packages added by a previous scenario in `ember try:each`. If `npm` does `prune` as part of install in newer versions, we just need to be sure of which versions of `npm` that we support.

**Comment by mansona** [comment]
I think it's worth considering dropping support for npm@4 because of issues like this 🤔 and considering that npm@4 is not shipped by default in any active Node version we should be able to require at least npm@5 for ember-try

It would mean that we need to update the npm version in the default blueprint 😖 https://github.com/ember-cli/ember-cli/pull/8426

**Comment by kellyselden** [comment]
> npm@4 is not shipped by default in any active Node version

Caveat is that it npm 3 is still active in node 6 for a few months 😛

**Comment by mansona** [comment]
I chose my words very carefully 😏 we 100% don't support npm@3 so we manually install npm@4 😂

**Comment by kategengler** [comment]
I don't think we can drop support for npm@4 when it is explicitly used in the current .travis.yml shipped in a new addon https://github.com/ember-cli/ember-addon-output/blob/v3.7.1/.travis.yml#L56

**Comment by kategengler** [comment]
I do think it would be ok to check npm version and do something different depending on the result.

**Comment by mansona** [comment]
So I have finally got https://github.com/ember-cli/ember-try/pull/281 failing the way that I want 😂 this is before any changes that fix the situation.

I will work on a fix later in the week 👍

**Comment by mansona** [comment]
I finally got #281 failing the way that I wanted and have applied the fix that we have talked about 🎉 

It seems like we're waiting for appveyor but it looks like it's going to take 9 hours to work through the backlog 🙈 and on top of that some of the builds are failing, it seems like they are now taking longer than max timeout: https://ci.appveyor.com/project/kategengler/ember-try/builds/22333001 

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by kategengler** [comment]
Appveyor has been incredibly flaky. I started working on swapping out to
azure pipelines late last week but haven't gotten back to it yet.
