### ISSUE TITLE
How might I get only one of my scenarios to run my after_success deploy script?

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-try#180]
Right now in my `.travis.yml` I have this

```
script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

after_success:
  - node_modules/.bin/ember deploy production
```

I think all the scenarios in my matrix are deploying (at least I'm getting Slack notifications for each).

Is it possible to do the deploy for one scenario? Or separately, after all of them have finished?

**Comment by kategengler** [comment]
This is definitely more in the realm of configuring travis than ember-try. 

The easiest way to do so would be forego use of the travis build matrix and instead use `ember try:each` ... then the `after_success` step would only be run after all scenarios had run and passed. 

Otherwise you may be able to use https://docs.travis-ci.com/user/build-stages (found from this open issue https://github.com/travis-ci/travis-ci/issues/929)

**Comment by rwjblue** [comment]
Another option is something like what I did in https://github.com/emberjs/data/pull/5342. It leverages Travis’s new build stages feature...

**Comment by samselikoff** [comment]
Awesome, figured someone here could point me in the right direction. Thanks yall!
