### ISSUE TITLE
`ember try:ember` dies after first failed scenario with 1.0.0-beta.3

### ISSUE THREAD

**Issue by pgengler** [ember-cli/ember-try#197]
When using ember-try 1.0.0-beta.3, `ember try:ember` exits immediately after a single scenario fails, without running the remaining scenarios or outputting the summary. (0.2.23 and 1.0.0-beta.1 work as expected.)

I created a new addon as a testcase, with a single failing test in it: https://github.com/pgengler/ember-try-testcase

To reproduce:
1) Clone the test addon and run `yarn install`.
2) Run `ember try:ember`. Only the "default" scenario runs, and execution stops with an error message displayed ([see output](https://gist.github.com/pgengler/e8d617a6cf43764b31593f8eac6b247d))

To see beta-1 behavior:
1) Check out the `beta-1` branch of the test addon and run `yarn install`.
2) Run `ember try:ember`. The scenarios all run to completion. ([see output](https://gist.github.com/pgengler/04c0c2cda6a00320dfde63549220c9f4))

**Comment by rwjblue** [comment]
> ember try:ember

Do you mean `try:each` here?

**Comment by kategengler** [comment]
`try:ember` is a command too ;) This should also affect `try:each`.

I haven't confirmed yet, but believe this to be the problem:
https://github.com/ember-cli/ember-try/blob/master/lib/utils/run.js#L20 needs to `.catch` to handle non-zero exit codes, rather than checking in `.then` (per https://github.com/sindresorhus/execa#usage)

No tests caught this because they either mock `run` OR don't test some failures, so we'll need a test for this too.
