### ISSUE TITLE
Stop backing up `node_modules`? 🤔

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-try#598]
When `ember-try`'s functionality was initially created, the package managers that existed at the time (IIRC it was npm@1 and npm@2) were extremely bad at ensuring the `node_modules` directory is laid out correctly. It was **very very bad** at fixing an invalid tree.

Current versions (for quite some time) do not have this issue, and backing up / restoring is quite a long time.

I'd like to remove the backup of `node_modules`...

Thoughts?

**Comment by alexlafroscia** [comment]
I would definitely be in favor of this; my one complaint with using `ember-try` is that it adds a lot of "time" overhead to running the tests. Especially in CI, where you often install all of the normal dependencies, then run `ember-try` and re-install all the dependencies again with a different `ember-source` version (and whatever else). In CI, it often doesn't matter if you've re-arranged `node_modules` since it's the only thing that will use them anyway! Anything that reduces the amount of overhead from this addon would be really welcome.

**Comment by mansona** [comment]
Ah yes I have found the other issue https://github.com/ember-cli/ember-try/issues/597 I will respond to your comment over there so as not to pollute this thread 👍
